wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
layer_10_size:
  desc: null
  value: 514
layer_1_size:
  desc: null
  value: 575
layer_2_size:
  desc: null
  value: 354
layer_3_size:
  desc: null
  value: 362
layer_4_size:
  desc: null
  value: 276
layer_5_size:
  desc: null
  value: 343
layer_6_size:
  desc: null
  value: 276
layer_7_size:
  desc: null
  value: 651
layer_8_size:
  desc: null
  value: 111
layer_9_size:
  desc: null
  value: 407
learning_rate:
  desc: null
  value: 1.000817562909363
lr_decay_epochs:
  desc: null
  value: 0
lr_schedule_type:
  desc: null
  value: plateau
